In [57]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import r2_score, accuracy_score, confusion_matrix

In [58]:
df = pd.read_csv('Tension_data_set_2024.csv')

In [59]:
df.head()

BP  BH  B2D   DH      T  D2H T_level
0  14   0   35  5.5  31.50   22       M
1  19   0   35  5.5  26.96   17       M
2  16   0   36  5.5  33.13   19       H
3  17   0   36  5.5  33.13   18       H
4  17   0   36  5.5  33.90   18       H

In [4]:
df['T_level'] = df['T_level'].map({'L':0, 'M':1, 'H':2 })

## Preparation

In [14]:
X = df.copy()
y = X.pop('T_level')

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X,y, random_state=0, test_size=0.3)

In [17]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train_sc = sc.fit_transform(X_train)
X_test_sc = sc.transform(X_test)

# Decision Tree Classifer

In [68]:
from sklearn.tree import DecisionTreeClassifier

In [69]:
dt = DecisionTreeClassifier()

In [70]:
dt.fit(X_train,y_train)

DecisionTreeClassifier()

In [71]:
dt_pred = dt.predict(X_test)

In [74]:
confusion_matrix(y_test, dt_pred)

array([[34,  0,  0],
       [ 0, 28,  0],
       [ 0,  0, 25]], dtype=int64)

In [76]:
accuracy_score(y_test, dt_pred)

1.0

In [77]:
{'actula': y_test.to_numpy(), 'predition': dt_pred}

{'actula': array([1, 2, 1, 0, 0, 1, 1, 0, 1, 0, 2, 0, 1, 1, 1, 0, 0, 0, 2, 2, 2, 0,
        1, 0, 1, 1, 0, 0, 1, 2, 0, 1, 2, 2, 1, 0, 1, 1, 0, 2, 1, 2, 0, 0,
        0, 1, 2, 0, 1, 0, 2, 0, 0, 0, 1, 2, 0, 1, 1, 0, 0, 2, 0, 2, 2, 2,
        0, 2, 0, 2, 2, 1, 0, 2, 0, 0, 2, 2, 1, 1, 0, 2, 2, 0, 1, 1, 1],
       dtype=int64),
 'predition': array([1, 2, 1, 0, 0, 1, 1, 0, 1, 0, 2, 0, 1, 1, 1, 0, 0, 0, 2, 2, 2, 0,
        1, 0, 1, 1, 0, 0, 1, 2, 0, 1, 2, 2, 1, 0, 1, 1, 0, 2, 1, 2, 0, 0,
        0, 1, 2, 0, 1, 0, 2, 0, 0, 0, 1, 2, 0, 1, 1, 0, 0, 2, 0, 2, 2, 2,
        0, 2, 0, 2, 2, 1, 0, 2, 0, 0, 2, 2, 1, 1, 0, 2, 2, 0, 1, 1, 1],
       dtype=int64)}

## Ranfom Forest

In [49]:
from sklearn.ensemble import RandomForestClassifier

In [50]:
rnf = RandomForestClassifier(n_estimators=300)

In [51]:
rnf.fit(X_train, y_train)

RandomForestClassifier(n_estimators=300)

In [52]:
rnf_pred = rnf.predict(X_test)

In [53]:
confusion_matrix(y_test, rnf_pred)

array([[34,  0,  0],
       [ 0, 28,  0],
       [ 0,  0, 25]], dtype=int64)

In [55]:
accuracy_score(y_test, rnf_pred)

1.0

In [66]:
{'actula': y_test.to_numpy(), 'predition': rnf_pred}

{'actula': array([1, 2, 1, 0, 0, 1, 1, 0, 1, 0, 2, 0, 1, 1, 1, 0, 0, 0, 2, 2, 2, 0,
        1, 0, 1, 1, 0, 0, 1, 2, 0, 1, 2, 2, 1, 0, 1, 1, 0, 2, 1, 2, 0, 0,
        0, 1, 2, 0, 1, 0, 2, 0, 0, 0, 1, 2, 0, 1, 1, 0, 0, 2, 0, 2, 2, 2,
        0, 2, 0, 2, 2, 1, 0, 2, 0, 0, 2, 2, 1, 1, 0, 2, 2, 0, 1, 1, 1],
       dtype=int64),
 'predition': array([1, 2, 1, 0, 0, 1, 1, 0, 1, 0, 2, 0, 1, 1, 1, 0, 0, 0, 2, 2, 2, 0,
        1, 0, 1, 1, 0, 0, 1, 2, 0, 1, 2, 2, 1, 0, 1, 1, 0, 2, 1, 2, 0, 0,
        0, 1, 2, 0, 1, 0, 2, 0, 0, 0, 1, 2, 0, 1, 1, 0, 0, 2, 0, 2, 2, 2,
        0, 2, 0, 2, 2, 1, 0, 2, 0, 0, 2, 2, 1, 1, 0, 2, 2, 0, 1, 1, 1],
       dtype=int64)}

# svm

In [78]:
from sklearn.svm import SVC

In [79]:
svc = SVC()

In [80]:
svc.fit(X_train_sc, y_train)

SVC()

In [81]:
svc_pred = svc.predict(X_test_sc)

In [82]:
accuracy_score(y_test, svr_pred)

0.9770114942528736

In [83]:
confusion_matrix(y_test,svc_pred )

array([[34,  0,  0],
       [ 0, 26,  2],
       [ 0,  0, 25]], dtype=int64)

In [84]:
{'actula': y_test.to_numpy(), 'predition': svc_pred}

{'actula': array([1, 2, 1, 0, 0, 1, 1, 0, 1, 0, 2, 0, 1, 1, 1, 0, 0, 0, 2, 2, 2, 0,
        1, 0, 1, 1, 0, 0, 1, 2, 0, 1, 2, 2, 1, 0, 1, 1, 0, 2, 1, 2, 0, 0,
        0, 1, 2, 0, 1, 0, 2, 0, 0, 0, 1, 2, 0, 1, 1, 0, 0, 2, 0, 2, 2, 2,
        0, 2, 0, 2, 2, 1, 0, 2, 0, 0, 2, 2, 1, 1, 0, 2, 2, 0, 1, 1, 1],
       dtype=int64),
 'predition': array([1, 2, 1, 0, 0, 1, 1, 0, 1, 0, 2, 0, 1, 1, 1, 0, 0, 0, 2, 2, 2, 0,
        1, 0, 1, 1, 0, 0, 1, 2, 0, 1, 2, 2, 1, 0, 1, 1, 0, 2, 1, 2, 0, 0,
        0, 1, 2, 0, 1, 0, 2, 0, 0, 0, 1, 2, 0, 1, 1, 0, 0, 2, 0, 2, 2, 2,
        0, 2, 0, 2, 2, 1, 0, 2, 0, 0, 2, 2, 1, 1, 0, 2, 2, 0, 2, 1, 2],
       dtype=int64)}

In [ ]:
#

# ANN

In [28]:
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Dense

In [30]:
df.shape

(288, 7)

In [41]:
ann = Sequential()
ann.add(Dense(64, input_shape=(X_train_sc.shape[1],), activation='relu'))
ann.add(Dense(400, kernel_initializer='normal',  activation ='relu' ))
ann.add(Dense(300, kernel_initializer='normal',  activation ='relu' ))
ann.add(Dense(100, kernel_initializer='normal', activation='relu'  ))
ann.add(Dense(50, kernel_initializer='normal', activation='relu'  ))
ann.add(Dense(1, kernel_initializer='normal', activation='softmax'))

In [42]:
ann.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy']   )
history = ann.fit(X_train_sc, y_train, epochs=600, verbose=0)

In [ ]:
# history = model.fit(X_train_sc, y_train, epochs=100, batch_size=10, verbose=2, validation_split=0.1)


In [43]:
ann_pred = ann.predict(X_test_sc)

3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step


C:\Users\Toufique\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\ops\nn.py:545: UserWarning: You are using a softmax over axis -1 of a tensor of shape (32, 1). This axis has size 1. The softmax operation will always return the value 1, which is likely not what you intended. Did you mean to use a sigmoid instead?
  warnings.warn(


In [44]:
test_loss, test_acc = ann.evaluate(X_test_sc, y_test, verbose=2)

3/3 - 0s - 80ms/step - accuracy: 0.3218 - loss: 0.0000e+00


In [45]:
test_loss

0.0

In [46]:
test_acc

0.3218390941619873

In [47]:
confusion_matrix(y_test, ann_pred)

array([[ 0, 34,  0],
       [ 0, 28,  0],
       [ 0, 25,  0]], dtype=int64)

In [87]:
{'actula': y_test.to_numpy(), 'predition': ann_pred.ravel()}

{'actula': array([1, 2, 1, 0, 0, 1, 1, 0, 1, 0, 2, 0, 1, 1, 1, 0, 0, 0, 2, 2, 2, 0,
        1, 0, 1, 1, 0, 0, 1, 2, 0, 1, 2, 2, 1, 0, 1, 1, 0, 2, 1, 2, 0, 0,
        0, 1, 2, 0, 1, 0, 2, 0, 0, 0, 1, 2, 0, 1, 1, 0, 0, 2, 0, 2, 2, 2,
        0, 2, 0, 2, 2, 1, 0, 2, 0, 0, 2, 2, 1, 1, 0, 2, 2, 0, 1, 1, 1],
       dtype=int64),
 'predition': array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1.], dtype=float32)}

In [88]:
accuracy_score(y_test, ann_pred)

0.3218390804597701